config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  get 'top/main'
  get 'top/login'
  get 'user/index'
  get 'user/mypage'
  post 'top/login'
  post 'user', to: 'user#create'
  post 'top/login'
  post 'top/main'
  get  'top/logout'
  get 'likes/create'
  
  resources :users do
    member do
      get :liking, :likers
    end
  end
  resources :user
  resources :chat
  resources :rooms
  resources :likes
  resources :relationships,       only: [:create, :destroy]
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  #belongs_to :user

end

app/models/message.rb
class Message < ApplicationRecord

  # createの後にコミットする { MessageBroadcastJobのperformを遅延実行 引数はself }
  after_create_commit { MessageBroadcastJob.perform_later self }

  belongs_to :room, optional: true
  belongs_to :user, optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :liker, class_name: "User"
  belongs_to :liked, class_name: "User"
  validates :liker_id, presence: true
  validates :liked_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
      has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
    
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "liker_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "liked_id",
                                   dependent:   :destroy
  has_many :liking, through: :active_relationships, source: :liked
  has_many :likers, through: :passive_relationships, source: :liker
  # ユーザーをフォローする
  def like(other_user)
    active_relationships.create(liked_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unlike(other_user)
    active_relationships.find_by(liked_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def liking?(other_user)
    liking.include?(other_user)
  end

  #  has_many :like_users,source: :user
  #  has_many :likes
    
  #def like(user)
  #  likes.create(user_id: user.id)
  #end
  
  #def unlike(user)
  #  likes.find_by(user_id: user.id).destroy
  #end
  
  #def liked?(user)
  #  like_users.include?(user)
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    

    
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    @rooms = Room.all.order(:id)
    @users = User.all
  end

  def create
    userd = User.find(params[:user_id])
    user = User.find_by(uid: session[:login_uid])
    unless userd.liking?(user)
     userd.like(user)
    end
    redirect_to top_main_path
  end
  
  def destroy
    userd = User.find(params[:id])
    user = User.find_by(uid: session[:login_uid])
    userd.unlike(user)
    redirect_to root_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:id])
    current_user = User.find_by(uid: session[:login_uid])
    current_user.like(user)
    redirect_to top_main_path
  end

  def destroy
    user = Relationship.find_by(liked_id: params[:id]).liked
    current_user = User.find_by(uid: session[:login_uid])
    current_user.unlike(user)
    redirect_to top_main_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @users = User.all
    @rooms = Room.all.order(:id)
  end


  def new
    @users = User.all
    @room = Room.new
    @rooms = Room.all.order(:id)
    render "new"
  end

  def create
      title = params[:room][:title]
      comment = params[:room][:comment]
      @room = Room.new(title: title,comment: comment)
      @rooms = Room.all.order(:id)
      @users = User.all
    if @room.save
      flash[:info] = 'ルームを作成しました。'
      render top_main_path
    else
      render new_room_path
    end
  end
  
  def show
    # メッセージ一覧を取得
    @rooms = Room.all.order(:id)
    @room = Room.find(params[:id])
    @users = User.all
    @messages = @room.messages
    user = User.find_by_uid(session[:login_uid])
    session[:login_name]=user.name
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

 def index
    @rooms = Room.all.order(:id)
    @users = User.all
 end

 def main
    @rooms = Room.all.order(:id)
    @users = User.all
      if session[:login_uid] != nil
        flash[:notice] = "ログインに成功しました"
        render'top/main'    
      else
        session[:login_uid] = nil
        flash[:notice] = "ログインに失敗しました"
        render top_main_path
      end
 end
  
 def login
    @users = User.all
    @rooms = Room.all.order(:id)
    if user = User.find_by_uid(params[:uid])
        if params[:uid] == user.uid && BCrypt::Password.new(user.pass) == params[:pass]
          session[:login_uid] = user.uid
          session[:login_name]=user.name
          session[:login_id]=user.id
          render top_main_path
        else
          flash[:notice] = "IDかパスワードが違います"
          render top_login_path
        end
    end
 end
 
 def logout
  session[:login_uid] = nil
  redirect_to '/'
 end

 def mypage
   user = User.find_by_uid(session[:login_uid])
   session[:login_name]=user.name
 end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
    @rooms = Room.all.order(:id)
  end

  def new
    @user = User.new
    render "new"
  end

  def create
      uid = params[:user][:uid]
      name = params[:user][:name]
      pass = params[:user][:pass]
      text = params[:user][:text]
      signup_password = BCrypt::Password.create(pass)
      @user = User.new(uid: uid,name: name,pass: signup_password,text: text)
    if @user.save
      flash[:info] = 'ユーザを登録完了しました。'
      redirect_to '/'
    else
      render new_user_path
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
  def update
    user = User.find_by(uid: session[:login_uid])
    user.name = params[:user][:name]
    user.text = params[:user][:text]
    user.save
    render '/user/index'
  end
  def mypage
    @user = User.find_by(uid: session[:login_uid])
    session[:text] = @user.text
    session[:name] = @user.name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class='message'>
  <%# 投稿者を特定できるようにメールアドレスを表示させておく %>
  <p><%= "#{message.user_id} #{message.content}" %></p>
</div>

app/views/rooms/_room.html.erb
<div>
  <ul>
    <% @rooms.each do |room| %>
      <li><%= link_to "部屋名：#{room.title}　　　　コメント：#{room.comment}", room_path(room) %></li>
    <% end %>
  </ul>
</div>

app/views/rooms/new.html.erb
<br>
<a class="btn-back" href='/'>戻る</a>
<% if @room.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @room.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div style="text-align: center;">
<%= form_for @room, url: {action: :create} do |f| %>
  <div style="font-size: 20px">
  <%= f.label :title, '部屋名' %><br>
  <%= f.text_field :title %> <br><br>
  <%= f.label :comment, 'コメント' %><br>
  <%= f.text_field :comment %> <br><br>
  </div>
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  <%= f.submit '登録' %>
<% end %>
</div>

app/views/rooms/show.html.erb
<h1>チャットルーム</h1>
<u><%= 'アカウント名'%>&emsp;  <%= "#{session[:login_name]}"%>&emsp;&emsp;<br></u>
<%= "部屋名：#{@room.title}" %>
<br>
<%= "コメント：#{@room.comment}" %>

<br><br>
<div id='messages' data-room_id="<%= @room.id %>">
  <%= render @messages %>
</div>

<%= label_tag :content, 'チャット入力:' %>
<%= text_field_tag :content, nil, data: { behavior: 'room_speaker' } %>
<br>
<a class="btn-logout" href='../top/main'>戻る</a>

app/views/top/index.html.erb
<h1>GMチャット</h1>
<p>GMチャットは色々なゲームについて話し合うためのサイトです。
お好きなゲームについてのルームを作成してチャットやマルチプレイをを楽しむことができます。</p>
<br><br>
<div style="text-align: center;">
<a class="btn-login" href='top/login'>ログイン</a><br><br>
<a class="btn-user" href='user/new'>ユーザー登録</a>
</div>

app/views/top/login.html.erb
<br>
<% if flash[:notice]%>
  <p><font color="black"><span style="font-weight:bold;"><%= flash[:notice] %></span></front></p>
<% end %>

<a class="btn-back" href='/'>戻る</a>
<div style="text-align: center;">
<%= form_tag'/top/login', method: :post do %>
 <div style="font-size: 20px">
 <%= label_tag :uid, 'ユーザーID' %><br>
 <%= text_field_tag :uid %><br><br>
 <%= label_tag :pass, 'パスワード' %><br>
 <%= password_field_tag :pass %><br><br>
 &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
 &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
 &emsp;&emsp;&emsp;
 <%= submit_tag 'ログイン' %>
 </div>
<% end %>
</div>

app/views/top/main.html.erb
<u><%='ユーザー名'%>&emsp; <%= "#{session[:login_name]}"%>&emsp;&emsp;<br></u>
<p1>ログイン中</p1>
<div style="text-align: left;">
<a class="btn-mypage" href='/user#index'>マイページ</a>
</div>
<br>
お気に入りユーザー
<% @users.each do |t| %>
    <p>
    <% if Relationship.find_by(liked_id: t.id) %>
      <% if session[:login_name] != t.name %>
    　　<%= t.name %>
      <% end %>
    <% end %>
    </p>
<% end %>
<hr>
<br><br>

<%= render "rooms/room" %>
<br>
<a class="btn-mypage" href='../rooms/new'>ルーム作成</a>
<br><br>
<hr>
<a class="btn-logout" href='../top/logout'>ログアウト</a>
<br>
<br>
<br>

ユーザー一覧
<% @users.each do |t| %>
    <p>
    <% if session[:login_name] != t.name %>
      <% if Relationship.find_by(liked_id: t.id) %>
        <%= link_to '★', relationship_path(t), method: :delete %>
      <% else %>
        <%= link_to '☆', relationships_path(id: t.id), method: :post %>
      <% end %>
            <%= t.name %>
    <% end %>
    </p>
<% end %>

app/views/user/eva.html.erb
<br>
<a class="btn-back" href='top/main'>戻る</a>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<a class="btn-mypage" href= '/user/mypage' >マイページの編集</a><br<br>
<br><br><br><br>
<div style="font-size: 20px">
  ユーザー名：
  <%= "#{session[:name]}"%>&emsp;&emsp;<br><br>
  ユーザーID：
  <%= "#{session[:login_uid]}"%>&emsp;&emsp;<br><br>
  ひとこと：
  <%= "#{session[:text]}"%>&emsp;&emsp;<br>
</div>

app/views/user/index.html.erb
<br>
<a class="btn-back" href='../top/main'>戻る</a>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<a class="btn-mypage" href= '/user/mypage' >マイページの編集</a><br<br>
<br><br><br><br>
<div style="font-size: 20px">
  ユーザー名：
  <%= "#{session[:name]}"%>&emsp;&emsp;<br><br>
  ユーザーID：
  <%= "#{session[:login_uid]}"%>&emsp;&emsp;<br><br>
  ひとこと：
  <%= "#{session[:text]}"%>&emsp;&emsp;<br>
</div>

app/views/user/mypage.html.erb
<br>
<div style="text-align: center;">
<%= form_for @user, url: {action: :mypage} do |f| %>
  <div style="font-size: 20px">
    <%= f.label :name, 'ユーザー名' %><br>
    <%= f.text_field :name %> <br><br>
    <%= f.label :text, 'コメント' %><br>
    <%= f.text_area :text ,size: "70×30" %> <br><br>
  </div><br><br>
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  <%= f.submit '登録' %>
<% end %>
</div>

app/views/user/new.html.erb
<br>
<a class="btn-back" href='/'>戻る</a>
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div style="text-align: center;">
<%= form_for @user, url: {action: :create} do |f| %>
  <div style="font-size: 20px">
  <%= f.label :uid, 'ユーザーID' %><br>
  <%= f.text_field :uid %> <br><br>
  <%= f.label :name, 'ユーザー名' %><br>
  <%= f.text_field :name %> <br><br>
  <%= f.label :pass, 'パスワード' %><br>
  <%= f.password_field :pass %> <br><br>
  <%= f.label :password_confirmation, 'パスワード（確認）' %><br>
  <%= f.password_field :password_confirmation %><br><br>
  </div>
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  <%= f.submit '登録' %>
<% end %>
</div>